import Footer from "@/components/HeaderAndFooter/Footer"
import NavigationHeader from "@/components/HeaderAndFooter/NavigationHeader"
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

const navigationData = [
  {name: "overview", title: "Overview", path: "/reports/overview"},
  {name: "analysis", title: "Analysis", path: "/reports/analysis"},
  {name: "findings", title: "Findings", path: "/reports/findings"},
  {
    name: "recommendations",
    title: "Recommendations",
    path: "/reports/recommendations",
  },
]

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavigationHeader data={navigationData} bgColor="bg-black" color="text-green-500" />
        <div> {children}</div>
        <Footer />
      </body>
    </html>
  )
}
